CREATE TABLE rag_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    document_type VARCHAR(50) NOT NULL,
    reference_id BIGINT NOT NULL REFERENCES book_paragraph(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    source_order_start INTEGER NOT NULL,
    source_order_end INTEGER NOT NULL,
    page_number_start INTEGER NOT NULL,
    page_number_end INTEGER NOT NULL,
    embedding vector(1536) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    strategy_version VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_rag_document_type CHECK (document_type = 'PARAGRAPH'),
    CONSTRAINT uk_rag_paragraph_strategy UNIQUE (book_id, reference_id, strategy_version)
);

CREATE INDEX idx_rag_document_book_active ON rag_document(book_id, active);

