CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_key VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(500),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE book_page (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    page_number INTEGER NOT NULL CHECK (page_number >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_book_page_number UNIQUE (book_id, page_number)
);

CREATE TABLE book_paragraph (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    page_id BIGINT NOT NULL REFERENCES book_page(id) ON DELETE CASCADE,
    paragraph_index INTEGER NOT NULL CHECK (paragraph_index >= 1),
    source_order INTEGER NOT NULL CHECK (source_order >= 1),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_page_paragraph_index UNIQUE (page_id, paragraph_index),
    CONSTRAINT uk_book_source_order UNIQUE (book_id, source_order)
);

CREATE TABLE book_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    page_id BIGINT NOT NULL REFERENCES book_page(id) ON DELETE CASCADE,
    image_order INTEGER NOT NULL CHECK (image_order >= 1),
    file_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_page_image_order UNIQUE (page_id, image_order)
);

CREATE INDEX idx_book_page_book_id ON book_page(book_id);
CREATE INDEX idx_book_paragraph_book_id ON book_paragraph(book_id);
CREATE INDEX idx_book_paragraph_page_id ON book_paragraph(page_id);
CREATE INDEX idx_book_image_book_id ON book_image(book_id);
CREATE INDEX idx_book_image_page_id ON book_image(page_id);
