CREATE TABLE entity_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    entity_type VARCHAR(30) NOT NULL CHECK (entity_type IN ('CHARACTER', 'PLACE', 'OBJECT', 'ORGANIZATION')),
    canonical_name VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED', 'MERGED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_entity_candidate_name UNIQUE (book_id, entity_type, canonical_name)
);

CREATE TABLE entity_mention (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_candidate_id BIGINT NOT NULL REFERENCES entity_candidate(id) ON DELETE CASCADE,
    paragraph_id BIGINT NOT NULL REFERENCES book_paragraph(id) ON DELETE CASCADE,
    mention_text VARCHAR(500) NOT NULL,
    source_type VARCHAR(30) NOT NULL DEFAULT 'TEXT' CHECK (source_type IN ('TEXT', 'IMAGE', 'TEXT_AND_IMAGE', 'INFERRED')),
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_entity_mention UNIQUE (entity_candidate_id, paragraph_id, mention_text)
);

CREATE INDEX idx_entity_candidate_book_id ON entity_candidate(book_id);
CREATE INDEX idx_entity_mention_candidate_id ON entity_mention(entity_candidate_id);
CREATE INDEX idx_entity_mention_paragraph_id ON entity_mention(paragraph_id);
