ALTER TABLE entity_candidate
    ADD COLUMN origin_source VARCHAR(30) NOT NULL DEFAULT 'TEXT'
        CHECK (origin_source IN ('TEXT', 'IMAGE'));

ALTER TABLE entity_mention
    ALTER COLUMN paragraph_id DROP NOT NULL,
    ADD COLUMN image_id BIGINT REFERENCES book_image(id) ON DELETE CASCADE;

ALTER TABLE entity_mention
    ADD CONSTRAINT ck_entity_mention_evidence CHECK (paragraph_id IS NOT NULL OR image_id IS NOT NULL);

CREATE UNIQUE INDEX uk_entity_mention_image
    ON entity_mention(entity_candidate_id, image_id, mention_text)
    WHERE image_id IS NOT NULL;

CREATE TABLE extracted_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    fact_type VARCHAR(40) NOT NULL CHECK (fact_type IN (
        'APPEARANCE', 'CLOTHING', 'EXPRESSION', 'ACTION', 'LOCATION',
        'INDOOR_OUTDOOR', 'WEATHER', 'TIME_OF_DAY', 'OBJECT'
    )),
    subject_candidate_id BIGINT REFERENCES entity_candidate(id) ON DELETE SET NULL,
    value TEXT NOT NULL,
    source_type VARCHAR(30) NOT NULL CHECK (source_type IN ('IMAGE', 'TEXT_AND_IMAGE')),
    status VARCHAR(30) NOT NULL CHECK (status IN ('CONFIRMED', 'CANDIDATE', 'UNKNOWN', 'CONFLICT')),
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    paragraph_id BIGINT REFERENCES book_paragraph(id) ON DELETE SET NULL,
    image_id BIGINT NOT NULL REFERENCES book_image(id) ON DELETE CASCADE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_extracted_fact_book_id ON extracted_fact(book_id);
CREATE INDEX idx_extracted_fact_subject ON extracted_fact(subject_candidate_id);
CREATE INDEX idx_extracted_fact_image ON extracted_fact(image_id);
