CREATE TABLE story_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    name VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    sequence_order INTEGER,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    evidence_paragraph_id BIGINT REFERENCES book_paragraph(id) ON DELETE SET NULL,
    evidence_image_id BIGINT REFERENCES book_image(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    entity_type VARCHAR(30) NOT NULL CHECK (entity_type IN ('CHARACTER', 'PLACE', 'OBJECT', 'ORGANIZATION', 'EVENT')),
    reference_type VARCHAR(30) NOT NULL CHECK (reference_type IN ('ENTITY_CANDIDATE', 'STORY_EVENT')),
    reference_id BIGINT NOT NULL,
    name VARCHAR(500) NOT NULL,
    description TEXT,
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_entity_reference UNIQUE (book_id, reference_type, reference_id)
);

CREATE TABLE event_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES story_event(id) ON DELETE CASCADE,
    knowledge_entity_id BIGINT NOT NULL REFERENCES knowledge_entity(id) ON DELETE CASCADE,
    participant_role VARCHAR(200) NOT NULL,
    evidence_paragraph_id BIGINT REFERENCES book_paragraph(id) ON DELETE SET NULL,
    evidence_image_id BIGINT REFERENCES book_image(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_event_participant UNIQUE (event_id, knowledge_entity_id, participant_role)
);

CREATE TABLE knowledge_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    source_entity_id BIGINT NOT NULL REFERENCES knowledge_entity(id) ON DELETE CASCADE,
    relation_type VARCHAR(100) NOT NULL,
    target_entity_id BIGINT NOT NULL REFERENCES knowledge_entity(id) ON DELETE CASCADE,
    description TEXT,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    review_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    evidence_paragraph_id BIGINT REFERENCES book_paragraph(id) ON DELETE SET NULL,
    evidence_image_id BIGINT REFERENCES book_image(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_knowledge_relation_distinct CHECK (source_entity_id <> target_entity_id)
);

CREATE INDEX idx_story_event_book ON story_event(book_id);
CREATE INDEX idx_knowledge_entity_book ON knowledge_entity(book_id);
CREATE INDEX idx_event_participant_event ON event_participant(event_id);
CREATE INDEX idx_knowledge_relation_book ON knowledge_relation(book_id);
CREATE INDEX idx_knowledge_relation_source ON knowledge_relation(source_entity_id);
CREATE INDEX idx_knowledge_relation_target ON knowledge_relation(target_entity_id);
