ALTER TABLE entity_candidate
    ADD COLUMN recommended_role VARCHAR(30) CHECK (recommended_role IN ('MAIN', 'SUPPORTING', 'MINOR', 'UNKNOWN')),
    ADD COLUMN role_recommendation_reason TEXT,
    ADD COLUMN merged_into_candidate_id BIGINT REFERENCES entity_candidate(id) ON DELETE SET NULL;

CREATE TABLE character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL UNIQUE REFERENCES entity_candidate(id) ON DELETE CASCADE,
    knowledge_entity_id BIGINT NOT NULL UNIQUE REFERENCES knowledge_entity(id) ON DELETE CASCADE,
    name VARCHAR(500) NOT NULL,
    narrative_role VARCHAR(30) NOT NULL CHECK (narrative_role IN ('MAIN', 'SUPPORTING', 'MINOR', 'UNKNOWN')),
    chat_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE character_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES character(id) ON DELETE CASCADE,
    alias VARCHAR(500) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    CONSTRAINT uk_character_alias UNIQUE (character_id, alias)
);

CREATE UNIQUE INDEX uk_book_single_chat_character ON character(book_id) WHERE chat_enabled = TRUE;
CREATE INDEX idx_character_book ON character(book_id);
