CREATE TABLE character_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL UNIQUE REFERENCES character(id) ON DELETE CASCADE,
    story_point VARCHAR(50) NOT NULL DEFAULT 'AFTER_FINAL_EVENT',
    role_description TEXT NOT NULL,
    appearance TEXT NOT NULL,
    personality TEXT NOT NULL,
    values_text TEXT NOT NULL,
    goals TEXT NOT NULL,
    speech_style TEXT NOT NULL,
    major_experiences TEXT NOT NULL,
    attitudes_toward_others TEXT NOT NULL,
    known_facts TEXT NOT NULL,
    system_prompt TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE profile_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_profile_id BIGINT NOT NULL REFERENCES character_profile(id) ON DELETE CASCADE,
    profile_field VARCHAR(50) NOT NULL CHECK (profile_field IN (
        'ROLE_DESCRIPTION', 'APPEARANCE', 'PERSONALITY', 'VALUES', 'GOALS', 'SPEECH_STYLE',
        'MAJOR_EXPERIENCES', 'ATTITUDES_TOWARD_OTHERS', 'KNOWN_FACTS'
    )),
    paragraph_id BIGINT REFERENCES book_paragraph(id) ON DELETE SET NULL,
    image_id BIGINT REFERENCES book_image(id) ON DELETE SET NULL,
    source_type VARCHAR(30) NOT NULL CHECK (source_type IN ('TEXT', 'IMAGE', 'TEXT_AND_IMAGE', 'INFERRED')),
    inference_type VARCHAR(20) NOT NULL CHECK (inference_type IN ('EXPLICIT', 'INFERRED')),
    description TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_profile_evidence_source CHECK (paragraph_id IS NOT NULL OR image_id IS NOT NULL)
);

CREATE INDEX idx_profile_evidence_profile ON profile_evidence(character_profile_id);
